# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b367af61ca6e77f4be9ce717dca7794f28ecc79c4a28ca0a19f510482383db159c13a0eeae74d16b4452a541f92895100ddf201345c1aa03263f97d1e709846

test:
  secret_key_base: 5e0efc1e612f657e13e9e38dbc98dbf6462371bcbdb7ca448066de25aea71937302f1fbb2303679f39078eb8cb71986b235c11e8c99695ecab466d62931c4496

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
